[package]
name = "nostr-proto"
version = "0.1.0"
edition = "2021"
authors = ["Mike Dilger <mike@mikedilger.com>"]
description = "Types for nostr protocol handling"
readme = "README.md"
keywords = [ "nostr" ]
license = "MIT"

[dependencies]
aes = "0.8"
base64 = "0.13"
cbc = { version = "0.1", features = [ "std" ] }
derive_more = "0.99"
hex = "0.4"
hmac = "0.12"
k256 = { version = "0.11", features = [ "schnorr" ] }
pbkdf2 = { version = "0.11", default-features = false, features = [ "hmac", "sha2", "std" ] }
rand_core = "0.6"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
sha2 = "0.10"
thiserror = "1.0"
zeroize = "1.5"
