[package]
name = "nostr-types"
version = "0.3.0-unstable"
edition = "2021"
authors = ["Mike Dilger <mike@mikedilger.com>"]
description = "Types for nostr protocol handling"
repository = "https://github.com/mikedilger/nostr-types"
documentation = "https://docs.rs/nostr-types"
readme = "README.md"
keywords = [ "nostr" ]
license = "MIT"

[dependencies]
aes = "0.8"
base64 = "0.13"
bech32 = "0.9"
cbc = { version = "0.1", features = [ "std" ] }
chacha20poly1305 = "0.10"
derive_more = "0.99"
hex = "0.4"
hmac = "0.12"
http = "0.2"
k256 = { version = "0.11", features = [ "schnorr" ] }
num_cpus = "1"
pbkdf2 = { version = "0.11", default-features = false, features = [ "hmac", "sha2", "std" ] }
rand = "0.8"
rand_core = "0.6"
reqwest = { version = "0.11", features = [ "blocking", "json"  ] }
rpassword = "7.2"
scrypt = "0.10"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
sha2 = "0.10"
thiserror = "1.0"
tungstenite = { version = "0.17", features = [ "rustls-tls-native-roots" ] }
zeroize = "1.5"

# Force scrypt to build with release-like speed even in dev mode
[profile.dev.package.scrypt]
opt-level = 3
debug-assertions = false
overflow-checks = false
