[package]
name = "nostr-proto"
version = "0.1.0"
edition = "2021"
authors = ["Mike Dilger <mike@mikedilger.com>"]
description = "Types for nostr protocol handling"
readme = "README.md"
keywords = [ "nostr" ]
license = "MIT"

[dependencies]
k256 = { version = "0.11", features = [ "schnorr" ] }
